### ISSUE TITLE
Center and Variability main checklist

### ISSUE THREAD

**Issue by chrisklus** [phetsims/center-and-variability#1]
# Center and Variability main checklist

## Design
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [ ] **Mockups complete** (Date: //)
  - [ ] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: //)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //)
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [ ] **Pre-prototype items**
  - [ ] Auxilary screenshots (at least 1 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate
  - [ ] Email/Twitter announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
- [ ] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Screen-specific screenshots for metadata service (see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827))
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [ ] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Make sim visible on website** 
   - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 02/01/2022)
  - [x] Simulation added to [responsible_dev.json](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.json)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 02/01/2022)
- [x] **Screen 1: Major features complete** (Date 02/16/2022) SR Hours = 65, CK Hours estimated around ~ 50
- [x] **Screen 2: Major features complete** (Date 02/25/2022)
- [x] **Sim is "feature complete"** (Date: //)
- [x] **QA team "first look"** (Date: //)
- [x] Interviews may happen around here (see above)
- [x] **Code review checklist completed"** (Date: //)
- [x] **Sim team sign-off** (Date: //)
- [x] **Code review completed** (Date: //)
- [x] **Sim dev test completed** (Date: //)
- [x] **Sim RC tests completed** (Date: //)
- [ ] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#screenshots))
  - [x] #8
  - [ ] Add CT tests for public query parameters
- [ ] **Published** (Date: //)

## QA
- [ ] *If a Port:* **Legacy sim tested for bugs**; issues reported in repo
- [x] **Dev testing started** (Date: //)
- [x] **Dev testing completed** (Date: //)
- [x] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: //)

**Comment by samreid** [comment]
@amanda-phet is this checklist useful to us anymore now that we have a published prototype? Just trying to clean up issues by closing non-useful ones.

**Comment by amanda-phet** [comment]
I am not 100% sure what the process is for prototype to full publication. Do we normally make a new checklist for the full sim? Looking at what is checked off, I think this is still useful, since many of these things aren't actually completed.

**Comment by amanda-phet** [comment]
Assigning to @samreid and @catherinecarter as someone will need to be on top of checking off items as we near final publication.

**Comment by samreid** [comment]
Will we publish (non-prototype) after "Spread" screen, or will there still be a 4th "Lab" screen?

**Comment by catherinecarter** [comment]
There will no longer be a 4th "lab" screen. Once the "Spread" screen is complete, we will publish.

**Comment by marlitas** [comment]
The sim has been published. I believe last steps are post-mortem. https://github.com/phetsims/center-and-variability/issues/597
